"""Source-labeled inputs for deterministic paper-figure regeneration.

These records transcribe accepted-paper plotting sources. They are not U280
measurements and must never be substituted for rows emitted by the hardware
measurement workflow. CSV and SVG files are generated from these constants.
"""

from __future__ import annotations

PAPER_REFERENCE_RECORD_COUNT = 668
MIGRATED_CSV_SHA256 = "b92cafe211f9f001f097898b1aae59c3c132ed6e9956176394fd14c034b3d147"

SOURCE_METADATA = {
    'vector_fig11': ('vector_geometry_digitization', 'e2f655b815ea93b42fd8b4d07a3338108b05d526538a508a06911ee8a44f9699'),
    'vector_fig12': ('vector_geometry_digitization', '03631bb354c124578afb69b94bca09c584300e28db6692d3f08578ea1bbc7051'),
    'vector_fig14': ('vector_geometry_digitization', '7899270127476690fd8215bb6c8a7fc329563deca39c9a447654f1c5d9018d70'),
    'vector_fig4': ('vector_geometry_digitization', 'c97190cf681525f096318bf78da17ddedc9d0c440b8544665953c792405acf5f2'),
    'workbook_a': ('exact_workbook_value', 'b1435a8afb1f73b7049922076ab87c8a0d3822f6c7372ccb67044f153784177f'),
    'workbook_b': ('exact_workbook_value', 'fb9c95a3e356b9e2c601c612941d7e66ee9c3fa7d1b92392c77ac57fa3d768cf'),
}

VALUE_NOTES = {
    'digitized_bar_boundary_01pp': 'Digitized from the vector bar boundary and calibrated axis; rounded to 0.1 percentage point.',
    'digitized_bar_uncertainty_002': 'Digitized from vector bar geometry; expected uncertainty is about +/-0.02 normalized unit.',
    'digitized_broken_axis_bar': 'Digitized from the vector bar geometry using the plotted broken-axis calibration.',
    'digitized_explicit_average_bar': 'Digitized from the explicit AVG bar, not recomputed from rounded point values.',
    'digitized_line_uncertainty_0002': 'Digitized from the vector line-marker geometry; expected uncertainty is about +/-0.002.',
    'digitized_line_uncertainty_001': 'Digitized from the vector line-marker geometry; expected uncertainty is about +/-0.01 speedup.',
    'exact_numeric_cell': 'Exact numeric cell from the author plotting workbook.',
    'exact_published_axis_order': 'Exact workbook value. Model blocks follow the published figure axis (JODIE, TGN, TGAT, APAN); two neighboring workbook labels are swapped.',
    'exact_wo_oats_label_normalized': 'Exact workbook value; workbook label WO/OASC is normalized to the paper label WO/OATS.',
    'explicit_average_cell': 'Explicit average cell from the author plotting workbook.',
    'explicit_overall_cell': 'Explicit overall cell from the author plotting workbook.',
}

# figure, model, dataset, solution, x, value, source_id, source_locator, note_id
PAPER_REFERENCE_ROWS = (
    ('fig2_execution_breakdown', 'JODIE', 'WK', 'TGS (%)', None, 6.5, 'workbook_a', 'Sheet1!C2', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WK', 'MG (%)', None, 4.8, 'workbook_a', 'Sheet1!D2', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WK', 'VMU (%)', None, 81.5, 'workbook_a', 'Sheet1!E2', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WK', 'TA (%)', None, 7.2, 'workbook_a', 'Sheet1!F2', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'MC', 'TGS (%)', None, 5.2, 'workbook_a', 'Sheet1!C3', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'MC', 'MG (%)', None, 5.1, 'workbook_a', 'Sheet1!D3', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'MC', 'VMU (%)', None, 80.8, 'workbook_a', 'Sheet1!E3', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'MC', 'TA (%)', None, 8.9, 'workbook_a', 'Sheet1!F3', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'RT', 'TGS (%)', None, 6.1, 'workbook_a', 'Sheet1!C4', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'RT', 'MG (%)', None, 4.5, 'workbook_a', 'Sheet1!D4', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'RT', 'VMU (%)', None, 82.2, 'workbook_a', 'Sheet1!E4', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'RT', 'TA (%)', None, 7.2, 'workbook_a', 'Sheet1!F4', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'LM', 'TGS (%)', None, 6.8, 'workbook_a', 'Sheet1!C5', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'LM', 'MG (%)', None, 5.5, 'workbook_a', 'Sheet1!D5', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'LM', 'VMU (%)', None, 78.5, 'workbook_a', 'Sheet1!E5', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'LM', 'TA (%)', None, 9.2, 'workbook_a', 'Sheet1!F5', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WT', 'TGS (%)', None, 10.5, 'workbook_a', 'Sheet1!C6', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WT', 'MG (%)', None, 3.2, 'workbook_a', 'Sheet1!D6', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WT', 'VMU (%)', None, 81.1, 'workbook_a', 'Sheet1!E6', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'WT', 'TA (%)', None, 5.2, 'workbook_a', 'Sheet1!F6', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'GT', 'TGS (%)', None, 14.2, 'workbook_a', 'Sheet1!C7', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'GT', 'MG (%)', None, 2.8, 'workbook_a', 'Sheet1!D7', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'GT', 'VMU (%)', None, 78.5, 'workbook_a', 'Sheet1!E7', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'JODIE', 'GT', 'TA (%)', None, 4.5, 'workbook_a', 'Sheet1!F7', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WK', 'TGS (%)', None, 72.5, 'workbook_a', 'Sheet1!C8', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WK', 'MG (%)', None, 4.2, 'workbook_a', 'Sheet1!D8', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WK', 'VMU (%)', None, 1.8, 'workbook_a', 'Sheet1!E8', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WK', 'TA (%)', None, 21.5, 'workbook_a', 'Sheet1!F8', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'MC', 'TGS (%)', None, 68.8, 'workbook_a', 'Sheet1!C9', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'MC', 'MG (%)', None, 4.8, 'workbook_a', 'Sheet1!D9', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'MC', 'VMU (%)', None, 2.1, 'workbook_a', 'Sheet1!E9', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'MC', 'TA (%)', None, 24.3, 'workbook_a', 'Sheet1!F9', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'RT', 'TGS (%)', None, 74.1, 'workbook_a', 'Sheet1!C10', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'RT', 'MG (%)', None, 3.9, 'workbook_a', 'Sheet1!D10', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'RT', 'VMU (%)', None, 1.5, 'workbook_a', 'Sheet1!E10', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'RT', 'TA (%)', None, 20.5, 'workbook_a', 'Sheet1!F10', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'LM', 'TGS (%)', None, 65.5, 'workbook_a', 'Sheet1!C11', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'LM', 'MG (%)', None, 5.2, 'workbook_a', 'Sheet1!D11', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'LM', 'VMU (%)', None, 2.5, 'workbook_a', 'Sheet1!E11', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'LM', 'TA (%)', None, 26.8, 'workbook_a', 'Sheet1!F11', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WT', 'TGS (%)', None, 80.2, 'workbook_a', 'Sheet1!C12', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WT', 'MG (%)', None, 3.1, 'workbook_a', 'Sheet1!D12', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WT', 'VMU (%)', None, 1.2, 'workbook_a', 'Sheet1!E12', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'WT', 'TA (%)', None, 15.5, 'workbook_a', 'Sheet1!F12', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'GT', 'TGS (%)', None, 84.5, 'workbook_a', 'Sheet1!C13', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'GT', 'MG (%)', None, 2.5, 'workbook_a', 'Sheet1!D13', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'GT', 'VMU (%)', None, 1.1, 'workbook_a', 'Sheet1!E13', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGAT', 'GT', 'TA (%)', None, 11.9, 'workbook_a', 'Sheet1!F13', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WK', 'TGS (%)', None, 44.5, 'workbook_a', 'Sheet1!C14', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WK', 'MG (%)', None, 5.8, 'workbook_a', 'Sheet1!D14', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WK', 'VMU (%)', None, 34.2, 'workbook_a', 'Sheet1!E14', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WK', 'TA (%)', None, 15.5, 'workbook_a', 'Sheet1!F14', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'MC', 'TGS (%)', None, 41.2, 'workbook_a', 'Sheet1!C15', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'MC', 'MG (%)', None, 6.5, 'workbook_a', 'Sheet1!D15', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'MC', 'VMU (%)', None, 33.5, 'workbook_a', 'Sheet1!E15', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'MC', 'TA (%)', None, 18.8, 'workbook_a', 'Sheet1!F15', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'RT', 'TGS (%)', None, 46.8, 'workbook_a', 'Sheet1!C16', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'RT', 'MG (%)', None, 5.2, 'workbook_a', 'Sheet1!D16', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'RT', 'VMU (%)', None, 34.8, 'workbook_a', 'Sheet1!E16', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'RT', 'TA (%)', None, 13.2, 'workbook_a', 'Sheet1!F16', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'LM', 'TGS (%)', None, 42.5, 'workbook_a', 'Sheet1!C17', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'LM', 'MG (%)', None, 6.1, 'workbook_a', 'Sheet1!D17', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'LM', 'VMU (%)', None, 32.5, 'workbook_a', 'Sheet1!E17', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'LM', 'TA (%)', None, 18.9, 'workbook_a', 'Sheet1!F17', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WT', 'TGS (%)', None, 55.4, 'workbook_a', 'Sheet1!C18', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WT', 'MG (%)', None, 4.2, 'workbook_a', 'Sheet1!D18', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WT', 'VMU (%)', None, 29.8, 'workbook_a', 'Sheet1!E18', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'WT', 'TA (%)', None, 10.6, 'workbook_a', 'Sheet1!F18', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'GT', 'TGS (%)', None, 61.2, 'workbook_a', 'Sheet1!C19', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'GT', 'MG (%)', None, 3.5, 'workbook_a', 'Sheet1!D19', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'GT', 'VMU (%)', None, 27.5, 'workbook_a', 'Sheet1!E19', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'TGN', 'GT', 'TA (%)', None, 7.8, 'workbook_a', 'Sheet1!F19', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WK', 'TGS (%)', None, 54.5, 'workbook_a', 'Sheet1!C20', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WK', 'MG (%)', None, 5.8, 'workbook_a', 'Sheet1!D20', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WK', 'VMU (%)', None, 18.2, 'workbook_a', 'Sheet1!E20', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WK', 'TA (%)', None, 21.5, 'workbook_a', 'Sheet1!F20', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'MC', 'TGS (%)', None, 50.2, 'workbook_a', 'Sheet1!C21', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'MC', 'MG (%)', None, 6.5, 'workbook_a', 'Sheet1!D21', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'MC', 'VMU (%)', None, 17.5, 'workbook_a', 'Sheet1!E21', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'MC', 'TA (%)', None, 25.8, 'workbook_a', 'Sheet1!F21', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'RT', 'TGS (%)', None, 56.8, 'workbook_a', 'Sheet1!C22', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'RT', 'MG (%)', None, 5.2, 'workbook_a', 'Sheet1!D22', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'RT', 'VMU (%)', None, 19.5, 'workbook_a', 'Sheet1!E22', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'RT', 'TA (%)', None, 18.5, 'workbook_a', 'Sheet1!F22', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'LM', 'TGS (%)', None, 52.5, 'workbook_a', 'Sheet1!C23', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'LM', 'MG (%)', None, 6.1, 'workbook_a', 'Sheet1!D23', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'LM', 'VMU (%)', None, 16.8, 'workbook_a', 'Sheet1!E23', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'LM', 'TA (%)', None, 24.6, 'workbook_a', 'Sheet1!F23', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WT', 'TGS (%)', None, 62.4, 'workbook_a', 'Sheet1!C24', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WT', 'MG (%)', None, 4.2, 'workbook_a', 'Sheet1!D24', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WT', 'VMU (%)', None, 18.2, 'workbook_a', 'Sheet1!E24', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'WT', 'TA (%)', None, 15.2, 'workbook_a', 'Sheet1!F24', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'GT', 'TGS (%)', None, 68.5, 'workbook_a', 'Sheet1!C25', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'GT', 'MG (%)', None, 3.5, 'workbook_a', 'Sheet1!D25', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'GT', 'VMU (%)', None, 15.8, 'workbook_a', 'Sheet1!E25', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'APAN', 'GT', 'TA (%)', None, 12.2, 'workbook_a', 'Sheet1!F25', 'exact_numeric_cell'),
    ('fig2_execution_breakdown', 'AVG', 'AVG', 'TGS (%)', None, 47.1, 'workbook_a', 'Sheet1!C26', 'explicit_average_cell'),
    ('fig2_execution_breakdown', 'AVG', 'AVG', 'MG (%)', None, 4.7, 'workbook_a', 'Sheet1!D26', 'explicit_average_cell'),
    ('fig2_execution_breakdown', 'AVG', 'AVG', 'VMU (%)', None, 33.0, 'workbook_a', 'Sheet1!E26', 'explicit_average_cell'),
    ('fig2_execution_breakdown', 'AVG', 'AVG', 'TA (%)', None, 15.2, 'workbook_a', 'Sheet1!F26', 'explicit_average_cell'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'WK', 'BPR (%)', None, 79.4, 'vector_fig4', 'Fig.4(a) bar:WK', 'digitized_bar_boundary_01pp'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'MC', 'BPR (%)', None, 73.3, 'vector_fig4', 'Fig.4(a) bar:MC', 'digitized_bar_boundary_01pp'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'RT', 'BPR (%)', None, 76.8, 'vector_fig4', 'Fig.4(a) bar:RT', 'digitized_bar_boundary_01pp'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'LM', 'BPR (%)', None, 68.3, 'vector_fig4', 'Fig.4(a) bar:LM', 'digitized_bar_boundary_01pp'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'WT', 'BPR (%)', None, 88.6, 'vector_fig4', 'Fig.4(a) bar:WT', 'digitized_bar_boundary_01pp'),
    ('fig4a_branch_parallelism_ratio', 'ALL', 'GT', 'BPR (%)', None, 91.2, 'vector_fig4', 'Fig.4(a) bar:GT', 'digitized_bar_boundary_01pp'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WK', 'Warp divergence', None, 38.2, 'workbook_b', 'Sheet1!J3', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WK', 'Dependency synchronization', None, 37.5, 'workbook_b', 'Sheet1!K3', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WK', 'Dynamic dependency bookkeeping', None, 24.3, 'workbook_b', 'Sheet1!L3', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'MC', 'Warp divergence', None, 40.5, 'workbook_b', 'Sheet1!J4', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'MC', 'Dependency synchronization', None, 36.2, 'workbook_b', 'Sheet1!K4', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'MC', 'Dynamic dependency bookkeeping', None, 23.3, 'workbook_b', 'Sheet1!L4', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'RT', 'Warp divergence', None, 42.1, 'workbook_b', 'Sheet1!J5', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'RT', 'Dependency synchronization', None, 34.8, 'workbook_b', 'Sheet1!K5', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'RT', 'Dynamic dependency bookkeeping', None, 23.1, 'workbook_b', 'Sheet1!L5', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'LM', 'Warp divergence', None, 55.4, 'workbook_b', 'Sheet1!J6', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'LM', 'Dependency synchronization', None, 27.5, 'workbook_b', 'Sheet1!K6', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'LM', 'Dynamic dependency bookkeeping', None, 17.1, 'workbook_b', 'Sheet1!L6', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WT', 'Warp divergence', None, 34.6, 'workbook_b', 'Sheet1!J7', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WT', 'Dependency synchronization', None, 38.5, 'workbook_b', 'Sheet1!K7', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'WT', 'Dynamic dependency bookkeeping', None, 26.9, 'workbook_b', 'Sheet1!L7', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'GT', 'Warp divergence', None, 29.3, 'workbook_b', 'Sheet1!J8', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'GT', 'Dependency synchronization', None, 51.5, 'workbook_b', 'Sheet1!K8', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'JODIE', 'GT', 'Dynamic dependency bookkeeping', None, 19.2, 'workbook_b', 'Sheet1!L8', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WK', 'Warp divergence', None, 35.8, 'workbook_b', 'Sheet1!J9', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WK', 'Dependency synchronization', None, 34.8, 'workbook_b', 'Sheet1!K9', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WK', 'Dynamic dependency bookkeeping', None, 29.4, 'workbook_b', 'Sheet1!L9', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'MC', 'Warp divergence', None, 38.2, 'workbook_b', 'Sheet1!J10', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'MC', 'Dependency synchronization', None, 33.6, 'workbook_b', 'Sheet1!K10', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'MC', 'Dynamic dependency bookkeeping', None, 28.2, 'workbook_b', 'Sheet1!L10', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'RT', 'Warp divergence', None, 40.5, 'workbook_b', 'Sheet1!J11', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'RT', 'Dependency synchronization', None, 31.5, 'workbook_b', 'Sheet1!K11', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'RT', 'Dynamic dependency bookkeeping', None, 28.0, 'workbook_b', 'Sheet1!L11', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'LM', 'Warp divergence', None, 52.6, 'workbook_b', 'Sheet1!J12', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'LM', 'Dependency synchronization', None, 25.4, 'workbook_b', 'Sheet1!K12', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'LM', 'Dynamic dependency bookkeeping', None, 22.0, 'workbook_b', 'Sheet1!L12', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WT', 'Warp divergence', None, 32.1, 'workbook_b', 'Sheet1!J13', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WT', 'Dependency synchronization', None, 35.5, 'workbook_b', 'Sheet1!K13', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'WT', 'Dynamic dependency bookkeeping', None, 32.4, 'workbook_b', 'Sheet1!L13', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'GT', 'Warp divergence', None, 26.8, 'workbook_b', 'Sheet1!J14', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'GT', 'Dependency synchronization', None, 48.7, 'workbook_b', 'Sheet1!K14', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGN', 'GT', 'Dynamic dependency bookkeeping', None, 24.5, 'workbook_b', 'Sheet1!L14', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WK', 'Warp divergence', None, 74.8, 'workbook_b', 'Sheet1!J15', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WK', 'Dependency synchronization', None, 8.1, 'workbook_b', 'Sheet1!K15', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WK', 'Dynamic dependency bookkeeping', None, 17.1, 'workbook_b', 'Sheet1!L15', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'MC', 'Warp divergence', None, 76.5, 'workbook_b', 'Sheet1!J16', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'MC', 'Dependency synchronization', None, 7.4, 'workbook_b', 'Sheet1!K16', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'MC', 'Dynamic dependency bookkeeping', None, 16.1, 'workbook_b', 'Sheet1!L16', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'RT', 'Warp divergence', None, 78.2, 'workbook_b', 'Sheet1!J17', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'RT', 'Dependency synchronization', None, 6.5, 'workbook_b', 'Sheet1!K17', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'RT', 'Dynamic dependency bookkeeping', None, 15.3, 'workbook_b', 'Sheet1!L17', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'LM', 'Warp divergence', None, 84.6, 'workbook_b', 'Sheet1!J18', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'LM', 'Dependency synchronization', None, 5.2, 'workbook_b', 'Sheet1!K18', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'LM', 'Dynamic dependency bookkeeping', None, 10.2, 'workbook_b', 'Sheet1!L18', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WT', 'Warp divergence', None, 70.4, 'workbook_b', 'Sheet1!J19', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WT', 'Dependency synchronization', None, 10.6, 'workbook_b', 'Sheet1!K19', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'WT', 'Dynamic dependency bookkeeping', None, 19.0, 'workbook_b', 'Sheet1!L19', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'GT', 'Warp divergence', None, 64.5, 'workbook_b', 'Sheet1!J20', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'GT', 'Dependency synchronization', None, 15.3, 'workbook_b', 'Sheet1!K20', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'TGAT', 'GT', 'Dynamic dependency bookkeeping', None, 20.2, 'workbook_b', 'Sheet1!L20', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WK', 'Warp divergence', None, 41.5, 'workbook_b', 'Sheet1!J21', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WK', 'Dependency synchronization', None, 36.2, 'workbook_b', 'Sheet1!K21', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WK', 'Dynamic dependency bookkeeping', None, 22.3, 'workbook_b', 'Sheet1!L21', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'MC', 'Warp divergence', None, 44.8, 'workbook_b', 'Sheet1!J22', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'MC', 'Dependency synchronization', None, 34.1, 'workbook_b', 'Sheet1!K22', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'MC', 'Dynamic dependency bookkeeping', None, 21.1, 'workbook_b', 'Sheet1!L22', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'RT', 'Warp divergence', None, 46.7, 'workbook_b', 'Sheet1!J23', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'RT', 'Dependency synchronization', None, 32.5, 'workbook_b', 'Sheet1!K23', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'RT', 'Dynamic dependency bookkeeping', None, 20.8, 'workbook_b', 'Sheet1!L23', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'LM', 'Warp divergence', None, 58.2, 'workbook_b', 'Sheet1!J24', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'LM', 'Dependency synchronization', None, 25.6, 'workbook_b', 'Sheet1!K24', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'LM', 'Dynamic dependency bookkeeping', None, 16.2, 'workbook_b', 'Sheet1!L24', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WT', 'Warp divergence', None, 37.8, 'workbook_b', 'Sheet1!J25', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WT', 'Dependency synchronization', None, 39.8, 'workbook_b', 'Sheet1!K25', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'WT', 'Dynamic dependency bookkeeping', None, 22.4, 'workbook_b', 'Sheet1!L25', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'GT', 'Warp divergence', None, 32.5, 'workbook_b', 'Sheet1!J26', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'GT', 'Dependency synchronization', None, 48.2, 'workbook_b', 'Sheet1!K26', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'APAN', 'GT', 'Dynamic dependency bookkeeping', None, 19.3, 'workbook_b', 'Sheet1!L26', 'exact_numeric_cell'),
    ('fig9b_gpu_overhead_breakdown', 'AVG', 'AVG', 'Warp divergence', None, 49.1, 'workbook_b', 'Sheet1!J27', 'explicit_average_cell'),
    ('fig9b_gpu_overhead_breakdown', 'AVG', 'AVG', 'Dependency synchronization', None, 29.4, 'workbook_b', 'Sheet1!K27', 'explicit_average_cell'),
    ('fig9b_gpu_overhead_breakdown', 'AVG', 'AVG', 'Dynamic dependency bookkeeping', None, 21.5, 'workbook_b', 'Sheet1!L27', 'explicit_average_cell'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WK', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S31', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WK', 'Cascade', None, 5.42, 'workbook_b', 'Sheet1!T31', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WK', 'TempGNN-G', None, 11.15, 'workbook_b', 'Sheet1!U31', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WK', 'TempGNN', None, 128.4, 'workbook_b', 'Sheet1!V31', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'MC', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S32', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'MC', 'Cascade', None, 4.88, 'workbook_b', 'Sheet1!T32', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'MC', 'TempGNN-G', None, 9.64, 'workbook_b', 'Sheet1!U32', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'MC', 'TempGNN', None, 121.5, 'workbook_b', 'Sheet1!V32', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'RT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S33', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'RT', 'Cascade', None, 5.12, 'workbook_b', 'Sheet1!T33', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'RT', 'TempGNN-G', None, 10.25, 'workbook_b', 'Sheet1!U33', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'RT', 'TempGNN', None, 131.2, 'workbook_b', 'Sheet1!V33', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'LM', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S34', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'LM', 'Cascade', None, 4.65, 'workbook_b', 'Sheet1!T34', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'LM', 'TempGNN-G', None, 8.84, 'workbook_b', 'Sheet1!U34', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'LM', 'TempGNN', None, 108.6, 'workbook_b', 'Sheet1!V34', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S35', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WT', 'Cascade', None, 3.95, 'workbook_b', 'Sheet1!T35', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WT', 'TempGNN-G', None, 9.12, 'workbook_b', 'Sheet1!U35', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'WT', 'TempGNN', None, 152.4, 'workbook_b', 'Sheet1!V35', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'GT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S36', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'GT', 'Cascade', None, 3.82, 'workbook_b', 'Sheet1!T36', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'GT', 'TempGNN-G', None, 9.55, 'workbook_b', 'Sheet1!U36', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'JODIE', 'GT', 'TempGNN', None, 168.5, 'workbook_b', 'Sheet1!V36', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WK', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S37', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WK', 'Cascade', None, 4.95, 'workbook_b', 'Sheet1!T37', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WK', 'TempGNN-G', None, 10.22, 'workbook_b', 'Sheet1!U37', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WK', 'TempGNN', None, 132.8, 'workbook_b', 'Sheet1!V37', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'MC', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S38', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'MC', 'Cascade', None, 4.54, 'workbook_b', 'Sheet1!T38', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'MC', 'TempGNN-G', None, 8.95, 'workbook_b', 'Sheet1!U38', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'MC', 'TempGNN', None, 125.4, 'workbook_b', 'Sheet1!V38', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'RT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S39', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'RT', 'Cascade', None, 4.76, 'workbook_b', 'Sheet1!T39', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'RT', 'TempGNN-G', None, 9.42, 'workbook_b', 'Sheet1!U39', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'RT', 'TempGNN', None, 135.2, 'workbook_b', 'Sheet1!V39', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'LM', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S40', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'LM', 'Cascade', None, 4.25, 'workbook_b', 'Sheet1!T40', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'LM', 'TempGNN-G', None, 8.15, 'workbook_b', 'Sheet1!U40', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'LM', 'TempGNN', None, 112.5, 'workbook_b', 'Sheet1!V40', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S41', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WT', 'Cascade', None, 3.65, 'workbook_b', 'Sheet1!T41', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WT', 'TempGNN-G', None, 8.45, 'workbook_b', 'Sheet1!U41', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'WT', 'TempGNN', None, 158.6, 'workbook_b', 'Sheet1!V41', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'GT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S42', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'GT', 'Cascade', None, 3.48, 'workbook_b', 'Sheet1!T42', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'GT', 'TempGNN-G', None, 8.86, 'workbook_b', 'Sheet1!U42', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGN', 'GT', 'TempGNN', None, 175.2, 'workbook_b', 'Sheet1!V42', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WK', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S43', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WK', 'Cascade', None, 5.86, 'workbook_b', 'Sheet1!T43', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WK', 'TempGNN-G', None, 12.32, 'workbook_b', 'Sheet1!U43', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WK', 'TempGNN', None, 130.5, 'workbook_b', 'Sheet1!V43', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'MC', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S44', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'MC', 'Cascade', None, 5.35, 'workbook_b', 'Sheet1!T44', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'MC', 'TempGNN-G', None, 10.63, 'workbook_b', 'Sheet1!U44', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'MC', 'TempGNN', None, 123.6, 'workbook_b', 'Sheet1!V44', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'RT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S45', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'RT', 'Cascade', None, 5.49, 'workbook_b', 'Sheet1!T45', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'RT', 'TempGNN-G', None, 11.24, 'workbook_b', 'Sheet1!U45', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'RT', 'TempGNN', None, 133.4, 'workbook_b', 'Sheet1!V45', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'LM', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S46', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'LM', 'Cascade', None, 5.18, 'workbook_b', 'Sheet1!T46', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'LM', 'TempGNN-G', None, 10.04, 'workbook_b', 'Sheet1!U46', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'LM', 'TempGNN', None, 110.2, 'workbook_b', 'Sheet1!V46', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S47', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WT', 'Cascade', None, 4.28, 'workbook_b', 'Sheet1!T47', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WT', 'TempGNN-G', None, 10.07, 'workbook_b', 'Sheet1!U47', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'WT', 'TempGNN', None, 155.8, 'workbook_b', 'Sheet1!V47', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'GT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S48', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'GT', 'Cascade', None, 4.31, 'workbook_b', 'Sheet1!T48', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'GT', 'TempGNN-G', None, 10.68, 'workbook_b', 'Sheet1!U48', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'TGAT', 'GT', 'TempGNN', None, 171.4, 'workbook_b', 'Sheet1!V48', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WK', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S49', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WK', 'Cascade', None, 7.85, 'workbook_b', 'Sheet1!T49', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WK', 'TempGNN-G', None, 15.42, 'workbook_b', 'Sheet1!U49', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WK', 'TempGNN', None, 115.6, 'workbook_b', 'Sheet1!V49', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'MC', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S50', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'MC', 'Cascade', None, 7.12, 'workbook_b', 'Sheet1!T50', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'MC', 'TempGNN-G', None, 13.85, 'workbook_b', 'Sheet1!U50', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'MC', 'TempGNN', None, 105.8, 'workbook_b', 'Sheet1!V50', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'RT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S51', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'RT', 'Cascade', None, 7.45, 'workbook_b', 'Sheet1!T51', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'RT', 'TempGNN-G', None, 14.62, 'workbook_b', 'Sheet1!U51', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'RT', 'TempGNN', None, 118.4, 'workbook_b', 'Sheet1!V51', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'LM', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S52', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'LM', 'Cascade', None, 6.84, 'workbook_b', 'Sheet1!T52', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'LM', 'TempGNN-G', None, 12.54, 'workbook_b', 'Sheet1!U52', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'LM', 'TempGNN', None, 98.5, 'workbook_b', 'Sheet1!V52', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S53', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WT', 'Cascade', None, 5.95, 'workbook_b', 'Sheet1!T53', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WT', 'TempGNN-G', None, 12.85, 'workbook_b', 'Sheet1!U53', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'WT', 'TempGNN', None, 142.3, 'workbook_b', 'Sheet1!V53', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'GT', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S54', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'GT', 'Cascade', None, 6.12, 'workbook_b', 'Sheet1!T54', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'GT', 'TempGNN-G', None, 13.45, 'workbook_b', 'Sheet1!U54', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'APAN', 'GT', 'TempGNN', None, 156.4, 'workbook_b', 'Sheet1!V54', 'exact_published_axis_order'),
    ('fig10_speedup_tglite_cpu', 'AVG', 'AVG', 'TGLite-CPU', None, 1.0, 'workbook_b', 'Sheet1!S55', 'explicit_overall_cell'),
    ('fig10_speedup_tglite_cpu', 'AVG', 'AVG', 'Cascade', None, 5.22, 'workbook_b', 'Sheet1!T55', 'explicit_overall_cell'),
    ('fig10_speedup_tglite_cpu', 'AVG', 'AVG', 'TempGNN-G', None, 10.85, 'workbook_b', 'Sheet1!U55', 'explicit_overall_cell'),
    ('fig10_speedup_tglite_cpu', 'AVG', 'AVG', 'TempGNN', None, 132.8, 'workbook_b', 'Sheet1!V55', 'explicit_overall_cell'),
    ('fig11_speedup_matg', 'JODIE', 'WK', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/WK/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'MC', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/MC/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'RT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/RT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'LM', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/LM/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'WT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/WT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'GT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:JODIE/GT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WK', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/WK/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'MC', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/MC/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'RT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/RT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'LM', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/LM/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/WT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'GT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGN/GT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WK', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/WK/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'MC', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/MC/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'RT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/RT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'LM', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/LM/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/WT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'GT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:TGAT/GT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WK', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/WK/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'MC', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/MC/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'RT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/RT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'LM', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/LM/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/WT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'GT', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 bar:APAN/GT/MATG', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'AVG', 'AVG', 'MATG', None, 1.0, 'vector_fig11', 'Fig.11 AVG bar:MATG', 'digitized_explicit_average_bar'),
    ('fig11_speedup_matg', 'JODIE', 'WK', 'ViTeGNN', None, 1.4199, 'vector_fig11', 'Fig.11 bar:JODIE/WK/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'MC', 'ViTeGNN', None, 1.3789, 'vector_fig11', 'Fig.11 bar:JODIE/MC/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'RT', 'ViTeGNN', None, 1.4473, 'vector_fig11', 'Fig.11 bar:JODIE/RT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'LM', 'ViTeGNN', None, 1.3469, 'vector_fig11', 'Fig.11 bar:JODIE/LM/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'WT', 'ViTeGNN', None, 1.5158, 'vector_fig11', 'Fig.11 bar:JODIE/WT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'GT', 'ViTeGNN', None, 1.5981, 'vector_fig11', 'Fig.11 bar:JODIE/GT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WK', 'ViTeGNN', None, 1.4382, 'vector_fig11', 'Fig.11 bar:TGN/WK/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'MC', 'ViTeGNN', None, 1.3971, 'vector_fig11', 'Fig.11 bar:TGN/MC/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'RT', 'ViTeGNN', None, 1.4701, 'vector_fig11', 'Fig.11 bar:TGN/RT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'LM', 'ViTeGNN', None, 1.3697, 'vector_fig11', 'Fig.11 bar:TGN/LM/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WT', 'ViTeGNN', None, 1.5386, 'vector_fig11', 'Fig.11 bar:TGN/WT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'GT', 'ViTeGNN', None, 1.6483, 'vector_fig11', 'Fig.11 bar:TGN/GT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WK', 'ViTeGNN', None, 1.3469, 'vector_fig11', 'Fig.11 bar:TGAT/WK/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'MC', 'ViTeGNN', None, 1.3195, 'vector_fig11', 'Fig.11 bar:TGAT/MC/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'RT', 'ViTeGNN', None, 1.3788, 'vector_fig11', 'Fig.11 bar:TGAT/RT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'LM', 'ViTeGNN', None, 1.2784, 'vector_fig11', 'Fig.11 bar:TGAT/LM/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WT', 'ViTeGNN', None, 1.4199, 'vector_fig11', 'Fig.11 bar:TGAT/WT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'GT', 'ViTeGNN', None, 1.4793, 'vector_fig11', 'Fig.11 bar:TGAT/GT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WK', 'ViTeGNN', None, 1.4473, 'vector_fig11', 'Fig.11 bar:APAN/WK/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'MC', 'ViTeGNN', None, 1.4062, 'vector_fig11', 'Fig.11 bar:APAN/MC/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'RT', 'ViTeGNN', None, 1.4884, 'vector_fig11', 'Fig.11 bar:APAN/RT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'LM', 'ViTeGNN', None, 1.388, 'vector_fig11', 'Fig.11 bar:APAN/LM/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WT', 'ViTeGNN', None, 1.5569, 'vector_fig11', 'Fig.11 bar:APAN/WT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'GT', 'ViTeGNN', None, 1.6757, 'vector_fig11', 'Fig.11 bar:APAN/GT/ViTeGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'AVG', 'AVG', 'ViTeGNN', None, 1.4473, 'vector_fig11', 'Fig.11 AVG bar:ViTeGNN', 'digitized_explicit_average_bar'),
    ('fig11_speedup_matg', 'JODIE', 'WK', 'RTGA', None, 1.9495, 'vector_fig11', 'Fig.11 bar:JODIE/WK/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'MC', 'RTGA', None, 1.8765, 'vector_fig11', 'Fig.11 bar:JODIE/MC/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'RT', 'RTGA', None, 2.018, 'vector_fig11', 'Fig.11 bar:JODIE/RT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'LM', 'RTGA', None, 2.2464, 'vector_fig11', 'Fig.11 bar:JODIE/LM/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'WT', 'RTGA', None, 2.1458, 'vector_fig11', 'Fig.11 bar:JODIE/WT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'GT', 'RTGA', None, 2.0956, 'vector_fig11', 'Fig.11 bar:JODIE/GT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WK', 'RTGA', None, 1.9769, 'vector_fig11', 'Fig.11 bar:TGN/WK/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'MC', 'RTGA', None, 1.9176, 'vector_fig11', 'Fig.11 bar:TGN/MC/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'RT', 'RTGA', None, 2.0454, 'vector_fig11', 'Fig.11 bar:TGN/RT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'LM', 'RTGA', None, 2.2966, 'vector_fig11', 'Fig.11 bar:TGN/LM/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WT', 'RTGA', None, 2.1962, 'vector_fig11', 'Fig.11 bar:TGN/WT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'GT', 'RTGA', None, 2.1458, 'vector_fig11', 'Fig.11 bar:TGN/GT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WK', 'RTGA', None, 1.8491, 'vector_fig11', 'Fig.11 bar:TGAT/WK/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'MC', 'RTGA', None, 1.7989, 'vector_fig11', 'Fig.11 bar:TGAT/MC/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'RT', 'RTGA', None, 1.8993, 'vector_fig11', 'Fig.11 bar:TGAT/RT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'LM', 'RTGA', None, 2.1458, 'vector_fig11', 'Fig.11 bar:TGAT/LM/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WT', 'RTGA', None, 1.9495, 'vector_fig11', 'Fig.11 bar:TGAT/WT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'GT', 'RTGA', None, 1.9952, 'vector_fig11', 'Fig.11 bar:TGAT/GT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WK', 'RTGA', None, 1.9952, 'vector_fig11', 'Fig.11 bar:APAN/WK/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'MC', 'RTGA', None, 1.9495, 'vector_fig11', 'Fig.11 bar:APAN/MC/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'RT', 'RTGA', None, 2.0773, 'vector_fig11', 'Fig.11 bar:APAN/RT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'LM', 'RTGA', None, 2.3468, 'vector_fig11', 'Fig.11 bar:APAN/LM/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WT', 'RTGA', None, 2.2464, 'vector_fig11', 'Fig.11 bar:APAN/WT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'GT', 'RTGA', None, 2.1962, 'vector_fig11', 'Fig.11 bar:APAN/GT/RTGA', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'AVG', 'AVG', 'RTGA', None, 2.0591, 'vector_fig11', 'Fig.11 AVG bar:RTGA', 'digitized_explicit_average_bar'),
    ('fig11_speedup_matg', 'JODIE', 'WK', 'TempGNN', None, 7.8392, 'vector_fig11', 'Fig.11 bar:JODIE/WK/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'MC', 'TempGNN', None, 7.41, 'vector_fig11', 'Fig.11 bar:JODIE/MC/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'RT', 'TempGNN', None, 8.0902, 'vector_fig11', 'Fig.11 bar:JODIE/RT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'LM', 'TempGNN', None, 6.1408, 'vector_fig11', 'Fig.11 bar:JODIE/LM/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'WT', 'TempGNN', None, 8.6381, 'vector_fig11', 'Fig.11 bar:JODIE/WT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'JODIE', 'GT', 'TempGNN', None, 10.2361, 'vector_fig11', 'Fig.11 bar:JODIE/GT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WK', 'TempGNN', None, 7.9076, 'vector_fig11', 'Fig.11 bar:TGN/WK/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'MC', 'TempGNN', None, 7.5425, 'vector_fig11', 'Fig.11 bar:TGN/MC/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'RT', 'TempGNN', None, 8.241, 'vector_fig11', 'Fig.11 bar:TGN/RT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'LM', 'TempGNN', None, 6.3417, 'vector_fig11', 'Fig.11 bar:TGN/LM/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'WT', 'TempGNN', None, 8.9395, 'vector_fig11', 'Fig.11 bar:TGN/WT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGN', 'GT', 'TempGNN', None, 10.6379, 'vector_fig11', 'Fig.11 bar:TGN/GT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WK', 'TempGNN', None, 6.2412, 'vector_fig11', 'Fig.11 bar:TGAT/WK/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'MC', 'TempGNN', None, 5.9445, 'vector_fig11', 'Fig.11 bar:TGAT/MC/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'RT', 'TempGNN', None, 6.4421, 'vector_fig11', 'Fig.11 bar:TGAT/RT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'LM', 'TempGNN', None, 5.1455, 'vector_fig11', 'Fig.11 bar:TGAT/LM/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'WT', 'TempGNN', None, 6.8392, 'vector_fig11', 'Fig.11 bar:TGAT/WT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'TGAT', 'GT', 'TempGNN', None, 7.5425, 'vector_fig11', 'Fig.11 bar:TGAT/GT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WK', 'TempGNN', None, 8.1406, 'vector_fig11', 'Fig.11 bar:APAN/WK/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'MC', 'TempGNN', None, 7.7387, 'vector_fig11', 'Fig.11 bar:APAN/MC/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'RT', 'TempGNN', None, 8.4373, 'vector_fig11', 'Fig.11 bar:APAN/RT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'LM', 'TempGNN', None, 6.5425, 'vector_fig11', 'Fig.11 bar:APAN/LM/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'WT', 'TempGNN', None, 9.1403, 'vector_fig11', 'Fig.11 bar:APAN/WT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'APAN', 'GT', 'TempGNN', None, 10.8342, 'vector_fig11', 'Fig.11 bar:APAN/GT/TempGNN', 'digitized_bar_uncertainty_002'),
    ('fig11_speedup_matg', 'AVG', 'AVG', 'TempGNN', None, 7.7889, 'vector_fig11', 'Fig.11 AVG bar:TempGNN', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'TGLite-CPU', None, 160.472, 'vector_fig12', 'Fig.12 bar:JODIE/WK/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'TGLite-CPU', None, 150.236, 'vector_fig12', 'Fig.12 bar:JODIE/MC/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'TGLite-CPU', None, 170.788, 'vector_fig12', 'Fig.12 bar:JODIE/RT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'TGLite-CPU', None, 190.474, 'vector_fig12', 'Fig.12 bar:JODIE/LM/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'TGLite-CPU', None, 185.432, 'vector_fig12', 'Fig.12 bar:JODIE/WT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'TGLite-CPU', None, 216.615, 'vector_fig12', 'Fig.12 bar:JODIE/GT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'TGLite-CPU', None, 165.51, 'vector_fig12', 'Fig.12 bar:TGN/WK/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'TGLite-CPU', None, 155.196, 'vector_fig12', 'Fig.12 bar:TGN/MC/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'TGLite-CPU', None, 175.826, 'vector_fig12', 'Fig.12 bar:TGN/RT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'TGLite-CPU', None, 195.512, 'vector_fig12', 'Fig.12 bar:TGN/LM/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'TGLite-CPU', None, 190.395, 'vector_fig12', 'Fig.12 bar:TGN/WT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'TGLite-CPU', None, 221.577, 'vector_fig12', 'Fig.12 bar:TGN/GT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'TGLite-CPU', None, 115.511, 'vector_fig12', 'Fig.12 bar:TGAT/WK/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'TGLite-CPU', None, 110.236, 'vector_fig12', 'Fig.12 bar:TGAT/MC/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'TGLite-CPU', None, 120.787, 'vector_fig12', 'Fig.12 bar:TGAT/RT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'TGLite-CPU', None, 140.551, 'vector_fig12', 'Fig.12 bar:TGAT/LM/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'TGLite-CPU', None, 135.432, 'vector_fig12', 'Fig.12 bar:TGAT/WT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'TGLite-CPU', None, 150.393, 'vector_fig12', 'Fig.12 bar:TGAT/GT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'TGLite-CPU', None, 162.519, 'vector_fig12', 'Fig.12 bar:APAN/WK/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'TGLite-CPU', None, 152.204, 'vector_fig12', 'Fig.12 bar:APAN/MC/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'TGLite-CPU', None, 172.834, 'vector_fig12', 'Fig.12 bar:APAN/RT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'TGLite-CPU', None, 192.52, 'vector_fig12', 'Fig.12 bar:APAN/LM/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'TGLite-CPU', None, 187.4, 'vector_fig12', 'Fig.12 bar:APAN/WT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'TGLite-CPU', None, 218.583, 'vector_fig12', 'Fig.12 bar:APAN/GT/TGLite-CPU', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'TGLite-CPU', None, 168.186, 'vector_fig12', 'Fig.12 AVG bar:TGLite-CPU', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'Cascade', None, 30.475, 'vector_fig12', 'Fig.12 bar:JODIE/WK/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'Cascade', None, 28.505, 'vector_fig12', 'Fig.12 bar:JODIE/MC/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'Cascade', None, 32.522, 'vector_fig12', 'Fig.12 bar:JODIE/RT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'Cascade', None, 39.528, 'vector_fig12', 'Fig.12 bar:JODIE/LM/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'Cascade', None, 37.481, 'vector_fig12', 'Fig.12 bar:JODIE/WT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'Cascade', None, 49.472, 'vector_fig12', 'Fig.12 bar:JODIE/GT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'Cascade', None, 31.971, 'vector_fig12', 'Fig.12 bar:TGN/WK/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'Cascade', None, 30.0, 'vector_fig12', 'Fig.12 bar:TGN/MC/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'Cascade', None, 34.017, 'vector_fig12', 'Fig.12 bar:TGN/RT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'Cascade', None, 42.165, 'vector_fig12', 'Fig.12 bar:TGN/LM/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'Cascade', None, 38.977, 'vector_fig12', 'Fig.12 bar:TGN/WT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'Cascade', None, 52.627, 'vector_fig12', 'Fig.12 bar:TGN/GT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'Cascade', None, 21.499, 'vector_fig12', 'Fig.12 bar:TGAT/WK/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'Cascade', None, 20.239, 'vector_fig12', 'Fig.12 bar:TGAT/MC/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'Cascade', None, 23.073, 'vector_fig12', 'Fig.12 bar:TGAT/RT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'Cascade', None, 28.505, 'vector_fig12', 'Fig.12 bar:TGAT/LM/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'Cascade', None, 26.537, 'vector_fig12', 'Fig.12 bar:TGAT/WT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'Cascade', None, 31.97, 'vector_fig12', 'Fig.12 bar:TGAT/GT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'Cascade', None, 31.183, 'vector_fig12', 'Fig.12 bar:APAN/WK/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'Cascade', None, 29.213, 'vector_fig12', 'Fig.12 bar:APAN/MC/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'Cascade', None, 33.23, 'vector_fig12', 'Fig.12 bar:APAN/RT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'Cascade', None, 40.498, 'vector_fig12', 'Fig.12 bar:APAN/LM/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'Cascade', None, 38.189, 'vector_fig12', 'Fig.12 bar:APAN/WT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'Cascade', None, 50.966, 'vector_fig12', 'Fig.12 bar:APAN/GT/Cascade', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'Cascade', None, 33.545, 'vector_fig12', 'Fig.12 AVG bar:Cascade', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'MATG', None, 9.29, 'vector_fig12', 'Fig.12 bar:JODIE/WK/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'MATG', None, 8.975, 'vector_fig12', 'Fig.12 bar:JODIE/MC/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'MATG', None, 9.922, 'vector_fig12', 'Fig.12 bar:JODIE/RT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'MATG', None, 12.284, 'vector_fig12', 'Fig.12 bar:JODIE/LM/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'MATG', None, 11.576, 'vector_fig12', 'Fig.12 bar:JODIE/WT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'MATG', None, 14.331, 'vector_fig12', 'Fig.12 bar:JODIE/GT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'MATG', None, 9.605, 'vector_fig12', 'Fig.12 bar:TGN/WK/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'MATG', None, 9.212, 'vector_fig12', 'Fig.12 bar:TGN/MC/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'MATG', None, 10.237, 'vector_fig12', 'Fig.12 bar:TGN/RT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'MATG', None, 12.599, 'vector_fig12', 'Fig.12 bar:TGN/LM/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'MATG', None, 11.891, 'vector_fig12', 'Fig.12 bar:TGN/WT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'MATG', None, 14.567, 'vector_fig12', 'Fig.12 bar:TGN/GT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'MATG', None, 6.377, 'vector_fig12', 'Fig.12 bar:TGAT/WK/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'MATG', None, 6.062, 'vector_fig12', 'Fig.12 bar:TGAT/MC/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'MATG', None, 6.692, 'vector_fig12', 'Fig.12 bar:TGAT/RT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'MATG', None, 8.109, 'vector_fig12', 'Fig.12 bar:TGAT/LM/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'MATG', None, 7.401, 'vector_fig12', 'Fig.12 bar:TGAT/WT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'MATG', None, 8.739, 'vector_fig12', 'Fig.12 bar:TGAT/GT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'MATG', None, 9.369, 'vector_fig12', 'Fig.12 bar:APAN/WK/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'MATG', None, 9.133, 'vector_fig12', 'Fig.12 bar:APAN/MC/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'MATG', None, 10.001, 'vector_fig12', 'Fig.12 bar:APAN/RT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'MATG', None, 12.363, 'vector_fig12', 'Fig.12 bar:APAN/LM/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'MATG', None, 11.733, 'vector_fig12', 'Fig.12 bar:APAN/WT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'MATG', None, 14.41, 'vector_fig12', 'Fig.12 bar:APAN/GT/MATG', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'MATG', None, 10.237, 'vector_fig12', 'Fig.12 AVG bar:MATG', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'ViTeGNN', None, 8.109, 'vector_fig12', 'Fig.12 bar:JODIE/WK/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'ViTeGNN', None, 7.873, 'vector_fig12', 'Fig.12 bar:JODIE/MC/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'ViTeGNN', None, 8.739, 'vector_fig12', 'Fig.12 bar:JODIE/RT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'ViTeGNN', None, 10.867, 'vector_fig12', 'Fig.12 bar:JODIE/LM/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'ViTeGNN', None, 10.08, 'vector_fig12', 'Fig.12 bar:JODIE/WT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'ViTeGNN', None, 11.891, 'vector_fig12', 'Fig.12 bar:JODIE/GT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'ViTeGNN', None, 8.424, 'vector_fig12', 'Fig.12 bar:TGN/WK/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'ViTeGNN', None, 8.188, 'vector_fig12', 'Fig.12 bar:TGN/MC/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'ViTeGNN', None, 8.975, 'vector_fig12', 'Fig.12 bar:TGN/RT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'ViTeGNN', None, 11.182, 'vector_fig12', 'Fig.12 bar:TGN/LM/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'ViTeGNN', None, 10.395, 'vector_fig12', 'Fig.12 bar:TGN/WT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'ViTeGNN', None, 12.205, 'vector_fig12', 'Fig.12 bar:TGN/GT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'ViTeGNN', None, 5.432, 'vector_fig12', 'Fig.12 bar:TGAT/WK/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'ViTeGNN', None, 5.117, 'vector_fig12', 'Fig.12 bar:TGAT/MC/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'ViTeGNN', None, 5.669, 'vector_fig12', 'Fig.12 bar:TGAT/RT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'ViTeGNN', None, 6.928, 'vector_fig12', 'Fig.12 bar:TGAT/LM/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'ViTeGNN', None, 6.377, 'vector_fig12', 'Fig.12 bar:TGAT/WT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'ViTeGNN', None, 8.897, 'vector_fig12', 'Fig.12 bar:TGAT/GT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'ViTeGNN', None, 8.188, 'vector_fig12', 'Fig.12 bar:APAN/WK/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'ViTeGNN', None, 8.03, 'vector_fig12', 'Fig.12 bar:APAN/MC/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'ViTeGNN', None, 8.818, 'vector_fig12', 'Fig.12 bar:APAN/RT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'ViTeGNN', None, 11.024, 'vector_fig12', 'Fig.12 bar:APAN/LM/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'ViTeGNN', None, 10.237, 'vector_fig12', 'Fig.12 bar:APAN/WT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'ViTeGNN', None, 11.969, 'vector_fig12', 'Fig.12 bar:APAN/GT/ViTeGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'ViTeGNN', None, 8.897, 'vector_fig12', 'Fig.12 AVG bar:ViTeGNN', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'RTGA', None, 5.905, 'vector_fig12', 'Fig.12 bar:JODIE/WK/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'RTGA', None, 5.59, 'vector_fig12', 'Fig.12 bar:JODIE/MC/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'RTGA', None, 6.299, 'vector_fig12', 'Fig.12 bar:JODIE/RT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'RTGA', None, 8.031, 'vector_fig12', 'Fig.12 bar:JODIE/LM/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'RTGA', None, 7.401, 'vector_fig12', 'Fig.12 bar:JODIE/WT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'RTGA', None, 8.975, 'vector_fig12', 'Fig.12 bar:JODIE/GT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'RTGA', None, 6.062, 'vector_fig12', 'Fig.12 bar:TGN/WK/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'RTGA', None, 5.826, 'vector_fig12', 'Fig.12 bar:TGN/MC/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'RTGA', None, 6.535, 'vector_fig12', 'Fig.12 bar:TGN/RT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'RTGA', None, 8.188, 'vector_fig12', 'Fig.12 bar:TGN/LM/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'RTGA', None, 7.637, 'vector_fig12', 'Fig.12 bar:TGN/WT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'RTGA', None, 9.212, 'vector_fig12', 'Fig.12 bar:TGN/GT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'RTGA', None, 4.015, 'vector_fig12', 'Fig.12 bar:TGAT/WK/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'RTGA', None, 3.779, 'vector_fig12', 'Fig.12 bar:TGAT/MC/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'RTGA', None, 4.33, 'vector_fig12', 'Fig.12 bar:TGAT/RT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'RTGA', None, 5.275, 'vector_fig12', 'Fig.12 bar:TGAT/LM/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'RTGA', None, 4.724, 'vector_fig12', 'Fig.12 bar:TGAT/WT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'RTGA', None, 5.511, 'vector_fig12', 'Fig.12 bar:TGAT/GT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'RTGA', None, 5.983, 'vector_fig12', 'Fig.12 bar:APAN/WK/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'RTGA', None, 5.669, 'vector_fig12', 'Fig.12 bar:APAN/MC/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'RTGA', None, 6.377, 'vector_fig12', 'Fig.12 bar:APAN/RT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'RTGA', None, 8.109, 'vector_fig12', 'Fig.12 bar:APAN/LM/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'RTGA', None, 7.479, 'vector_fig12', 'Fig.12 bar:APAN/WT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'RTGA', None, 9.133, 'vector_fig12', 'Fig.12 bar:APAN/GT/RTGA', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'RTGA', None, 6.535, 'vector_fig12', 'Fig.12 AVG bar:RTGA', 'digitized_explicit_average_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WK', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/WK/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'MC', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/MC/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'RT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/RT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'LM', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/LM/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'WT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/WT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'JODIE', 'GT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:JODIE/GT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WK', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/WK/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'MC', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/MC/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'RT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/RT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'LM', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/LM/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'WT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/WT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGN', 'GT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGN/GT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WK', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/WK/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'MC', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/MC/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'RT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/RT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'LM', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/LM/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'WT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/WT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'TGAT', 'GT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:TGAT/GT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WK', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/WK/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'MC', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/MC/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'RT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/RT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'LM', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/LM/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'WT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/WT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'APAN', 'GT', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 bar:APAN/GT/TempGNN', 'digitized_broken_axis_bar'),
    ('fig12_energy_tempgnn', 'AVG', 'AVG', 'TempGNN', None, 1.0, 'vector_fig12', 'Fig.12 AVG bar:TempGNN', 'digitized_explicit_average_bar'),
    ('fig13_ablation_time', 'JODIE', 'WK', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J31', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'WK', 'WO/DDTC', None, 3.1, 'workbook_b', 'Sheet1!K31', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'WK', 'WO/OATS', None, 1.75, 'workbook_b', 'Sheet1!L31', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'MC', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J32', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'MC', 'WO/DDTC', None, 2.95, 'workbook_b', 'Sheet1!K32', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'MC', 'WO/OATS', None, 1.68, 'workbook_b', 'Sheet1!L32', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'RT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J33', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'RT', 'WO/DDTC', None, 3.25, 'workbook_b', 'Sheet1!K33', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'RT', 'WO/OATS', None, 1.82, 'workbook_b', 'Sheet1!L33', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'LM', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J34', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'LM', 'WO/DDTC', None, 2.65, 'workbook_b', 'Sheet1!K34', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'LM', 'WO/OATS', None, 1.55, 'workbook_b', 'Sheet1!L34', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'WT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J35', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'WT', 'WO/DDTC', None, 3.65, 'workbook_b', 'Sheet1!K35', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'WT', 'WO/OATS', None, 1.95, 'workbook_b', 'Sheet1!L35', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'GT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J36', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'GT', 'WO/DDTC', None, 4.25, 'workbook_b', 'Sheet1!K36', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'JODIE', 'GT', 'WO/OATS', None, 2.45, 'workbook_b', 'Sheet1!L36', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WK', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J37', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WK', 'WO/DDTC', None, 3.2, 'workbook_b', 'Sheet1!K37', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WK', 'WO/OATS', None, 1.8, 'workbook_b', 'Sheet1!L37', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'MC', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J38', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'MC', 'WO/DDTC', None, 3.05, 'workbook_b', 'Sheet1!K38', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'MC', 'WO/OATS', None, 1.75, 'workbook_b', 'Sheet1!L38', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'RT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J39', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'RT', 'WO/DDTC', None, 3.35, 'workbook_b', 'Sheet1!K39', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'RT', 'WO/OATS', None, 1.88, 'workbook_b', 'Sheet1!L39', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'LM', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J40', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'LM', 'WO/DDTC', None, 2.75, 'workbook_b', 'Sheet1!K40', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'LM', 'WO/OATS', None, 1.62, 'workbook_b', 'Sheet1!L40', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J41', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WT', 'WO/DDTC', None, 3.85, 'workbook_b', 'Sheet1!K41', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'WT', 'WO/OATS', None, 2.05, 'workbook_b', 'Sheet1!L41', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'GT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J42', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'GT', 'WO/DDTC', None, 4.45, 'workbook_b', 'Sheet1!K42', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGN', 'GT', 'WO/OATS', None, 2.55, 'workbook_b', 'Sheet1!L42', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WK', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J43', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WK', 'WO/DDTC', None, 2.15, 'workbook_b', 'Sheet1!K43', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WK', 'WO/OATS', None, 1.12, 'workbook_b', 'Sheet1!L43', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'MC', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J44', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'MC', 'WO/DDTC', None, 2.05, 'workbook_b', 'Sheet1!K44', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'MC', 'WO/OATS', None, 1.08, 'workbook_b', 'Sheet1!L44', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'RT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J45', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'RT', 'WO/DDTC', None, 2.25, 'workbook_b', 'Sheet1!K45', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'RT', 'WO/OATS', None, 1.15, 'workbook_b', 'Sheet1!L45', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'LM', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J46', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'LM', 'WO/DDTC', None, 1.85, 'workbook_b', 'Sheet1!K46', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'LM', 'WO/OATS', None, 1.05, 'workbook_b', 'Sheet1!L46', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J47', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WT', 'WO/DDTC', None, 2.45, 'workbook_b', 'Sheet1!K47', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'WT', 'WO/OATS', None, 1.18, 'workbook_b', 'Sheet1!L47', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'GT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J48', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'GT', 'WO/DDTC', None, 2.65, 'workbook_b', 'Sheet1!K48', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'TGAT', 'GT', 'WO/OATS', None, 1.25, 'workbook_b', 'Sheet1!L48', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WK', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J49', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WK', 'WO/DDTC', None, 3.25, 'workbook_b', 'Sheet1!K49', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WK', 'WO/OATS', None, 1.85, 'workbook_b', 'Sheet1!L49', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'MC', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J50', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'MC', 'WO/DDTC', None, 3.12, 'workbook_b', 'Sheet1!K50', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'MC', 'WO/OATS', None, 1.78, 'workbook_b', 'Sheet1!L50', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'RT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J51', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'RT', 'WO/DDTC', None, 3.42, 'workbook_b', 'Sheet1!K51', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'RT', 'WO/OATS', None, 1.92, 'workbook_b', 'Sheet1!L51', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'LM', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J52', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'LM', 'WO/DDTC', None, 2.82, 'workbook_b', 'Sheet1!K52', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'LM', 'WO/OATS', None, 1.65, 'workbook_b', 'Sheet1!L52', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J53', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WT', 'WO/DDTC', None, 3.95, 'workbook_b', 'Sheet1!K53', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'WT', 'WO/OATS', None, 2.12, 'workbook_b', 'Sheet1!L53', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'GT', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J54', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'GT', 'WO/DDTC', None, 4.55, 'workbook_b', 'Sheet1!K54', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'APAN', 'GT', 'WO/OATS', None, 2.65, 'workbook_b', 'Sheet1!L54', 'exact_wo_oats_label_normalized'),
    ('fig13_ablation_time', 'AVG', 'AVG', 'TempGNN', None, 1.0, 'workbook_b', 'Sheet1!J55', 'explicit_average_cell'),
    ('fig13_ablation_time', 'AVG', 'AVG', 'WO/DDTC', None, 3.08, 'workbook_b', 'Sheet1!K55', 'explicit_average_cell'),
    ('fig13_ablation_time', 'AVG', 'AVG', 'WO/OATS', None, 1.77, 'workbook_b', 'Sheet1!L55', 'explicit_average_cell'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'MATG', 400, 1.0, 'vector_fig14', 'Fig.14(a) marker:MATG/400', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'MATG', 600, 0.9201, 'vector_fig14', 'Fig.14(a) marker:MATG/600', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'MATG', 800, 0.865, 'vector_fig14', 'Fig.14(a) marker:MATG/800', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'MATG', 1000, 0.82, 'vector_fig14', 'Fig.14(a) marker:MATG/1000', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'MATG', 1200, 0.7952, 'vector_fig14', 'Fig.14(a) marker:MATG/1200', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'ViTeGNN', 400, 0.7801, 'vector_fig14', 'Fig.14(a) marker:ViTeGNN/400', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'ViTeGNN', 600, 0.685, 'vector_fig14', 'Fig.14(a) marker:ViTeGNN/600', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'ViTeGNN', 800, 0.6249, 'vector_fig14', 'Fig.14(a) marker:ViTeGNN/800', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'ViTeGNN', 1000, 0.5672, 'vector_fig14', 'Fig.14(a) marker:ViTeGNN/1000', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'ViTeGNN', 1200, 0.545, 'vector_fig14', 'Fig.14(a) marker:ViTeGNN/1200', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'RTGA', 400, 0.585, 'vector_fig14', 'Fig.14(a) marker:RTGA/400', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'RTGA', 600, 0.505, 'vector_fig14', 'Fig.14(a) marker:RTGA/600', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'RTGA', 800, 0.4449, 'vector_fig14', 'Fig.14(a) marker:RTGA/800', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'RTGA', 1000, 0.3989, 'vector_fig14', 'Fig.14(a) marker:RTGA/1000', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'RTGA', 1200, 0.3801, 'vector_fig14', 'Fig.14(a) marker:RTGA/1200', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'TempGNN', 400, 0.225, 'vector_fig14', 'Fig.14(a) marker:TempGNN/400', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'TempGNN', 600, 0.1649, 'vector_fig14', 'Fig.14(a) marker:TempGNN/600', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'TempGNN', 800, 0.1249, 'vector_fig14', 'Fig.14(a) marker:TempGNN/800', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'TempGNN', 1000, 0.1051, 'vector_fig14', 'Fig.14(a) marker:TempGNN/1000', 'digitized_line_uncertainty_0002'),
    ('fig14a_batch_sensitivity', 'ALL', 'AVG', 'TempGNN', 1200, 0.1021, 'vector_fig14', 'Fig.14(a) marker:TempGNN/1200', 'digitized_line_uncertainty_0002'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 2, 0.9989, 'vector_fig14', 'Fig.14(b) marker:WK/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 4, 1.5194, 'vector_fig14', 'Fig.14(b) marker:WK/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 6, 1.8493, 'vector_fig14', 'Fig.14(b) marker:WK/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 8, 2.1493, 'vector_fig14', 'Fig.14(b) marker:WK/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 16, 2.5489, 'vector_fig14', 'Fig.14(b) marker:WK/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 32, 2.5987, 'vector_fig14', 'Fig.14(b) marker:WK/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WK', 'TempGNN', 64, 2.5788, 'vector_fig14', 'Fig.14(b) marker:WK/64', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 2, 1.0004, 'vector_fig14', 'Fig.14(b) marker:MC/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 4, 1.5507, 'vector_fig14', 'Fig.14(b) marker:MC/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 6, 1.8806, 'vector_fig14', 'Fig.14(b) marker:MC/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 8, 2.1806, 'vector_fig14', 'Fig.14(b) marker:MC/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 16, 2.6214, 'vector_fig14', 'Fig.14(b) marker:MC/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 32, 2.6612, 'vector_fig14', 'Fig.14(b) marker:MC/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'MC', 'TempGNN', 64, 2.6513, 'vector_fig14', 'Fig.14(b) marker:MC/64', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 2, 0.9818, 'vector_fig14', 'Fig.14(b) marker:RT/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 4, 1.562, 'vector_fig14', 'Fig.14(b) marker:RT/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 6, 1.9019, 'vector_fig14', 'Fig.14(b) marker:RT/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 8, 2.2318, 'vector_fig14', 'Fig.14(b) marker:RT/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 16, 2.6825, 'vector_fig14', 'Fig.14(b) marker:RT/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 32, 2.7323, 'vector_fig14', 'Fig.14(b) marker:RT/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'RT', 'TempGNN', 64, 2.7024, 'vector_fig14', 'Fig.14(b) marker:RT/64', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 2, 0.9996, 'vector_fig14', 'Fig.14(b) marker:LM/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 4, 1.4205, 'vector_fig14', 'Fig.14(b) marker:LM/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 6, 1.6793, 'vector_fig14', 'Fig.14(b) marker:LM/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 8, 1.8201, 'vector_fig14', 'Fig.14(b) marker:LM/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 16, 1.9495, 'vector_fig14', 'Fig.14(b) marker:LM/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 32, 1.9794, 'vector_fig14', 'Fig.14(b) marker:LM/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'LM', 'TempGNN', 64, 1.9396, 'vector_fig14', 'Fig.14(b) marker:LM/64', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 2, 1.0174, 'vector_fig14', 'Fig.14(b) marker:WT/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 4, 1.6672, 'vector_fig14', 'Fig.14(b) marker:WT/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 6, 2.1678, 'vector_fig14', 'Fig.14(b) marker:WT/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 8, 2.5674, 'vector_fig14', 'Fig.14(b) marker:WT/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 16, 3.1674, 'vector_fig14', 'Fig.14(b) marker:WT/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 32, 3.2371, 'vector_fig14', 'Fig.14(b) marker:WT/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'WT', 'TempGNN', 64, 3.1973, 'vector_fig14', 'Fig.14(b) marker:WT/64', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 2, 1.0004, 'vector_fig14', 'Fig.14(b) marker:GT/2', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 4, 1.7213, 'vector_fig14', 'Fig.14(b) marker:GT/4', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 6, 2.3512, 'vector_fig14', 'Fig.14(b) marker:GT/6', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 8, 2.8503, 'vector_fig14', 'Fig.14(b) marker:GT/8', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 16, 3.5514, 'vector_fig14', 'Fig.14(b) marker:GT/16', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 32, 3.6509, 'vector_fig14', 'Fig.14(b) marker:GT/32', 'digitized_line_uncertainty_001'),
    ('fig14b_tdp_entries', 'ALL', 'GT', 'TempGNN', 64, 3.6111, 'vector_fig14', 'Fig.14(b) marker:GT/64', 'digitized_line_uncertainty_001'),
)
