#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${OUT_DIR}/information.txt"

{
  echo "TempGNN Artifact Environment Information"
  echo "======================================="
  echo
  echo "This file records the execution environment used to reproduce the main"
  echo "results of the TempGNN artifact. It includes system information, CPU/GPU/FPGA"
  echo "device information, compiler and toolchain versions, Python package versions,"
  echo "Git revision information, and default experimental settings."
  echo
  echo "The file is automatically generated by:"
  echo "    information/collect_env.sh"
  echo
  echo "The recorded environment corresponds to the platforms used in the paper:"
  echo "- FPGA: Xilinx Alveo U280"
  echo "- GPU: NVIDIA A100 (80 GB HBM2e)"
  echo "- CPU: Intel Xeon Platinum 8357B"
  echo
  echo "Default experiment settings:"
  echo "- Precision: FP32"
  echo "- Batch size: 1000"
  echo "- Models: JODIE, TGAT, TGN, APAN"
  echo "- Datasets: Wikipedia, MOOC, Reddit, LastFM, WikiTalk, GDELT"
  echo
  echo "For full reproduction steps, please refer to the repository README and the"
  echo "artifact run scripts under the corresponding experiment directories."
  echo
  echo "======================================="
  echo "Automatically Collected Environment Dump"
  echo "======================================="
  echo

  echo "[Timestamp]"
  date
  echo

  echo "[System]"
  echo "Hostname: $(hostname)"
  echo "OS:"
  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -d 2>/dev/null || true
  else
    echo "lsb_release not found"
  fi
  echo "Kernel: $(uname -r)"
  echo "Architecture: $(uname -m)"
  echo

  echo "[CPU]"
  if command -v lscpu >/dev/null 2>&1; then
    lscpu
  else
    echo "lscpu not found"
  fi
  echo

  echo "[Memory]"
  if command -v free >/dev/null 2>&1; then
    free -h
  else
    echo "free not found"
  fi
  echo

  echo "[GPU]"
  if command -v nvidia-smi >/dev/null 2>&1; then
    nvidia-smi
  else
    echo "nvidia-smi not found"
  fi
  echo

  echo "[FPGA]"
  if command -v xbutil >/dev/null 2>&1; then
    xbutil examine || true
  else
    echo "xbutil not found"
  fi
  echo

  echo "[Compilers and Toolchains]"

  echo "--- gcc ---"
  if command -v gcc >/dev/null 2>&1; then
    gcc --version
  else
    echo "gcc not found"
  fi
  echo

  echo "--- g++ ---"
  if command -v g++ >/dev/null 2>&1; then
    g++ --version
  else
    echo "g++ not found"
  fi
  echo

  echo "--- python ---"
  if command -v python3 >/dev/null 2>&1; then
    python3 --version
  else
    echo "python3 not found"
  fi
  echo

  echo "--- nvcc ---"
  if command -v nvcc >/dev/null 2>&1; then
    nvcc --version
  else
    echo "nvcc not found"
  fi
  echo

  echo "--- vitis ---"
  if command -v vitis >/dev/null 2>&1; then
    vitis -version || true
  else
    echo "vitis not found in PATH"
  fi
  echo

  echo "--- vivado ---"
  if command -v vivado >/dev/null 2>&1; then
    vivado -version || true
  else
    echo "vivado not found in PATH"
  fi
  echo

  echo "[Python Packages]"
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY' 2>/dev/null || echo "python package query failed"
pkgs = ["torch", "dgl", "numpy", "scipy", "pandas"]
for p in pkgs:
    try:
        m = __import__(p)
        print(f"{p}: {getattr(m, '__version__', 'unknown')}")
    except Exception as e:
        print(f"{p}: not found ({e})")
PY
  else
    echo "python3 not found"
  fi
  echo

  echo "[Git Revisions]"
  if command -v git >/dev/null 2>&1; then
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo "Repo root: $(git rev-parse --show-toplevel)"
      echo "Commit: $(git rev-parse HEAD)"
      echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
      echo "--- git status --short ---"
      git status --short || true
    else
      echo "Not inside a git repository"
    fi
  else
    echo "git not found"
  fi
  echo

  echo "[Experiment Defaults]"
  echo "Batch size: 1000"
  echo "Precision: FP32"
  echo "Models: JODIE, TGAT, TGN, APAN"
  echo "Datasets: Wikipedia, MOOC, Reddit, LastFM, WikiTalk, GDELT"
  echo "GPU prototype: TempGNN-G on NVIDIA A100 (80GB HBM2e)"
  echo "FPGA implementation: TempGNN on Xilinx Alveo U280"
  echo

  echo "[Notes]"
  echo "This file is automatically generated by information/collect_env.sh."
  echo "For full reproduction steps, please refer to the repository README and artifact run scripts."
} > "${OUT_FILE}"

echo "Environment information written to: ${OUT_FILE}"
